// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB_IwJm1GyK2PBOLkNZI9-EpDKcDHFs5Iw",
    authDomain: "messenger-mpv.firebaseapp.com",
    projectId: "messenger-mpv",
    storageBucket: "messenger-mpv.firebasestorage.app",
    messagingSenderId: "114218863625",
    appId: "1:114218863625:web:f6da557dbf8db5850afcd8",
    measurementId: "G-RCL0ZVS9NY"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB_IwJm1GyK2PBOLkNZI9-EpDKcDHFs5Iw",
    authDomain: "messenger-mpv.firebaseapp.com",
    projectId: "messenger-mpv",
    storageBucket: "messenger-mpv.firebasestorage.app",
    messagingSenderId: "114218863625",
    appId: "1:114218863625:android:f6da557dbf8db5850afcd8",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB_IwJm1GyK2PBOLkNZI9-EpDKcDHFs5Iw",
    authDomain: "messenger-mpv.firebaseapp.com",
    projectId: "messenger-mpv",
    storageBucket: "messenger-mpv.firebasestorage.app",
    messagingSenderId: "114218863625",
    appId: "1:114218863625:ios:f6da557dbf8db5850afcd8",
  );
} 